# Generated by Django 5.1.3 on 2025-03-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('100', '100'), ('200', '200'), ('300', '300')], max_length=200),
        ),
    ]
